### ISSUE TITLE
Raise repair issue when no data is available

### ISSUE THREAD

**Issue by kar-who** [golles/ha-kamstrup_403#130]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Hi,

I love this integration - and it has been working very reliable for the past year. Thank you!

However, it has happened that someone in my home has dislodged the IR sensor - and as a result no data was recorded to the energy dashboard. As I don't check the dashboard daily, it took me some time to realize this.

Would it be possible to raise a [repair issue in HA](https://developers.home-assistant.io/docs/core/platform/repairs/), whenever no data is being reported?

That would be great - thank you! :)

**Comment by golles** [comment]
Nice idea! Will try to add this in the future

**Comment by HAEdwin** [comment]
@kar-who I have had the same wish (even added it to a spinoff of this integration)

But then I realized three things: 

- This feature is not directly related to the main goal (reading the meter)
- I also wished for a notification on my phone
- I was overlooking exactly what Home Assistant is good at **Automations**.

I have had the fun to create an automation myself that adds the feature you requested in 2024. This works perfectly whenever I’m messing around in the meter cupboard again and accidentally move the IR sensor.

This automation monitors the event counter on state changes and sends a notification (even to phone if needed):
- The event counter increases when an event occurs (such as a battery status change). 
- The event counter becomes unavailable due to displacement

```
alias: Kamstrup IR-sensor monitor
description: ""
triggers:
  - entity_id:
      - sensor.kamstrup_403_infoevent_counter
    trigger: state
conditions: []
actions:
  - action: notify.<change to the entity of your phone or leave this action out>
    data:
      message: Kamstrup IR-sensor issue
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Kamstrup IR-sensor issue
mode: single
```

In my opinion this should be a good solution enough to close this feature request.
