### ISSUE TITLE
Integration in Energy dashboard

### ISSUE THREAD

**Issue by JeroenHaringman** [golles/ha-kamstrup_403#21]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Setting up this integration is well-documented, and it didn't take me long to have the Kamstrup data available in cards in the HA Overview dashboard. What I would like, though, is to integrate the measured values in the Energy dashboard, as this MQTT-based Kamstrup integration describes:

https://www.pieterbrinkman.com/2022/02/01/make-your-city-heating-stadsverwarming-smart-and-connect-it-home-assistant-energy-dashboard/

I don't have enough knowledge to build this myself though, so I hope it's possible that you could add some extra documentation which describes this process. Thank you very much.

**Comment by golles** [comment]
If I'm not mistaken the answer to your question was provided on tweakers, posting the template sensor here as well, in case anyone with the same question finds this issue.

```yaml
template:
  - sensor:
      - unique_id: gas_equivalent
        name: Stadsverwarming (m³)
        unit_of_measurement: m³
        device_class: gas
        state: >-
          {{ (states("sensor.kamstrup_403_heat_energy_e1") | float(0) * 3.6 / 1000 * 32.68) | round(2) }}
        state_class: total_increasing
        availability: >-
          {{ states("sensor.kamstrup_403_heat_energy_e1") | is_number }}
```
